package com.demo.flightbooking.ai;

import com.demo.flightbooking.utils.ConfigReader;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.model.ollama.OllamaChatModel;
import dev.langchain4j.model.openai.OpenAiChatModel;
import dev.langchain4j.service.AiServices;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Duration;

/**
 * AI-powered test scenario generator for the Flight Booking framework.
 *
 * WHAT IT DOES:
 * - Takes a feature description or change description as input
 * - Calls an LLM (Ollama local or OpenAI cloud) via LangChain4j
 * - Returns structured test scenarios in Markdown format
 * - Writes output to target/scenario-report.md
 *
 * WHAT IT DOES NOT DO:
 * - Does NOT generate executable Selenium code
 * - Does NOT modify any existing test or page object
 * - Does NOT run during test execution — this is a pre-test design tool
 *
 * THREE MODES:
 * 1. PRD → Comprehensive: Full coverage from a feature description
 * 2. Negative Only: Breaking scenarios — invalid inputs, boundary violations
 * 3. Regression Suite: Impact-aware scenarios after a code change
 *
 * ARCHITECTURE:
 * Same pattern as AiDataGenerator and AiFailureAnalyzer:
 * - ConfigReader-driven provider selection (ollama/openai)
 * - System property overrides for CI (-Dai.ollama.baseUrl=...)
 * - Decoupled from test execution — if LLM is down, existing tests still work
 *
 * USAGE:
 * - From IDE: Run ScenarioGeneratorRunner.main()
 * - From CLI: mvn exec:java -Dexec.mainClass="...ScenarioGeneratorRunner" -Dexec.classpathScope=test
 */
public class AiScenarioGenerator {

    private static final Logger logger = LogManager.getLogger(AiScenarioGenerator.class);

    private final ScenarioGeneratorService service;

    /**
     * Creates an AiScenarioGenerator using the provider configured in config.properties.
     * Same config-driven pattern as AiDataGenerator and AiFailureAnalyzer.
     */
    public AiScenarioGenerator() {
        this(buildModel());
    }

    /**
     * Creates an AiScenarioGenerator with an explicitly provided ChatModel.
     * Used for testing (mock models) and when you want to override the config.
     */
    public AiScenarioGenerator(ChatModel model) {
        this.service = AiServices.create(ScenarioGeneratorService.class, model);
        logger.info("AiScenarioGenerator initialized with model: {}", model.getClass().getSimpleName());
    }

    /**
     * Mode 1: PRD → Comprehensive test cases.
     * Generates full coverage: positive, negative, boundary, edge cases.
     *
     * @param feature The feature description or PRD text.
     * @return Path to the generated scenario report.
     */
    public Path generateFromPrd(String feature) {
        logger.info("=== Scenario Generation Started (Mode: PRD → Comprehensive) ===");
        logger.info("Feature input length: {} chars", feature.length());

        String scenarios = service.generateFromPrd(feature);
        validateOutputFormat(scenarios);

        String header = "# AI-Generated Test Scenarios — Comprehensive\n\n" +
                "> **Mode:** PRD → Comprehensive\n" +
                "> **Generated by:** AiScenarioGenerator\n" +
                "> **Model:** " + ConfigReader.getProperty("ai.ollama.model", "llama3.2") + "\n" +
                "> **Status:** DRAFT — requires human review before implementation\n\n" +
                "---\n\n";

        return writeReport(header + scenarios, "scenario-report-comprehensive.md");
    }

    /**
     * Mode 2: Negative testing only.
     * Generates breaking scenarios: invalid inputs, boundary violations, malformed data.
     *
     * @param feature The feature description to break.
     * @return Path to the generated scenario report.
     */
    public Path generateNegativeTests(String feature) {
        logger.info("=== Scenario Generation Started (Mode: Negative Testing) ===");
        logger.info("Feature input length: {} chars", feature.length());

        String scenarios = service.generateNegativeTests(feature);
        validateOutputFormat(scenarios);

        String header = "# AI-Generated Test Scenarios — Negative Testing\n\n" +
                "> **Mode:** Negative Testing Only\n" +
                "> **Generated by:** AiScenarioGenerator\n" +
                "> **Model:** " + ConfigReader.getProperty("ai.ollama.model", "llama3.2") + "\n" +
                "> **Status:** DRAFT — requires human review before implementation\n\n" +
                "---\n\n";

        return writeReport(header + scenarios, "scenario-report-negative.md");
    }

    /**
     * Mode 3: Regression suite after a code change.
     * Generates prioritized scenarios aware of existing tests.
     *
     * @param changeDescription What changed in the codebase.
     * @return Path to the generated scenario report.
     */
    public Path generateRegressionSuite(String changeDescription) {
        logger.info("=== Scenario Generation Started (Mode: Regression Suite) ===");
        logger.info("Change description length: {} chars", changeDescription.length());

        String scenarios = service.generateRegressionSuite(changeDescription);
        validateOutputFormat(scenarios);

        String header = "# AI-Generated Test Scenarios — Regression Suite\n\n" +
                "> **Mode:** Regression Suite (post-change)\n" +
                "> **Generated by:** AiScenarioGenerator\n" +
                "> **Model:** " + ConfigReader.getProperty("ai.ollama.model", "llama3.2") + "\n" +
                "> **Status:** DRAFT — requires human review before implementation\n\n" +
                "---\n\n";

        return writeReport(header + scenarios, "scenario-report-regression.md");
    }

    private static final String TABLE_MARKER = "| TID |";

    /**
     * Light sanity check on AI output format.
     * Same defensive pattern as AiDataGenerator's null passenger check (line 149-153).
     *
     * NOT strict validation — just awareness logging. The LLM may break table format
     * (observed with llama3.2 ignoring section headers).
     * This warns the user but does NOT block report generation.
     */
    private void validateOutputFormat(String scenarios) {
        if (scenarios == null || scenarios.isBlank()) {
            logger.warn("AI returned empty output — report will have no scenarios");
        } else if (!scenarios.contains(TABLE_MARKER)) {
            logger.warn("AI output may not follow expected table format (missing '{}' marker). " +
                    "Review the generated report carefully.", TABLE_MARKER);
        } else {
            logger.info("Output format check passed — table marker found");
        }
    }

    /**
     * Writes the scenario report to target/ directory.
     * Same location pattern as AiFailureAnalyzer (target/failure-analysis-report.md).
     */
    private Path writeReport(String content, String fileName) {
        Path outputPath = Paths.get("target", fileName);

        try {
            Files.createDirectories(outputPath.getParent());
            Files.writeString(outputPath, content);
            logger.info("Report written to: {}", outputPath.toAbsolutePath());
            logger.info("=== Scenario Generation Complete. Report: {} ===", outputPath);
        } catch (IOException e) {
            logger.error("Failed to write scenario report: {}", outputPath, e);
            throw new RuntimeException("Failed to write scenario report", e);
        }

        return outputPath;
    }

    /**
     * Builds the ChatModel from config.properties.
     * IDENTICAL to AiDataGenerator.buildModel() and AiFailureAnalyzer.buildModel().
     *
     * NOTE: This is intentionally duplicated, not extracted to a shared utility.
     * Why? Each AI utility is independently removable. If you delete scenario generation,
     * data generation and failure analysis still compile. No hidden coupling between layers.
     */
    private static ChatModel buildModel() {
        String provider = ConfigReader.getProperty("ai.provider", "ollama");

        return switch (provider.toLowerCase()) {
            case "openai" -> {
                String apiKey = System.getenv("OPENAI_API_KEY");
                if (apiKey == null || apiKey.isBlank()) {
                    throw new IllegalStateException(
                            "OPENAI_API_KEY environment variable is not set. " +
                                    "Set it or switch to ai.provider=ollama in config.properties"
                    );
                }
                String model = ConfigReader.getProperty("ai.openai.model", "gpt-4o");
                logger.info("Using OpenAI provider with model: {}", model);
                yield OpenAiChatModel.builder()
                        .apiKey(apiKey)
                        .modelName(model)
                        .temperature(0.3) // Slightly higher than data gen for creative scenario coverage
                        .build();
            }
            case "ollama" -> {
                String baseUrl = ConfigReader.getProperty("ai.ollama.baseUrl", "http://localhost:11434");
                String model = ConfigReader.getProperty("ai.ollama.model", "llama3.2");
                logger.info("Using Ollama provider at {} with model: {}", baseUrl, model);
                yield OllamaChatModel.builder()
                        .baseUrl(baseUrl)
                        .modelName(model)
                        .temperature(0.3)
                        .timeout(Duration.ofSeconds(300))
                        .build();
            }
            default -> throw new IllegalArgumentException(
                    "Unknown AI provider: " + provider +
                            ". Supported: 'ollama' (local, free) or 'openai' (cloud, paid)"
            );
        };
    }
}
