package com.demo.flightbooking.ai;

import com.demo.flightbooking.utils.ConfigReader;
import dev.langchain4j.model.chat.ChatModel;
import dev.langchain4j.model.ollama.OllamaChatModel;
import dev.langchain4j.model.openai.OpenAiChatModel;
import dev.langchain4j.service.AiServices;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.nio.file.*;
import java.time.Duration;

/**
 * AI Test Summary Generator
 *
 * PURPOSE:
 * - Reads surefire XML results
 * - Generates executive summary
 * - Writes to target/ai-summary-report.md
 *
 * IMPORTANT:
 * - Advisory only (does NOT affect build)
 * - No dependency on test execution
 */
public class AiTestSummaryGenerator {

    private static final Logger logger = LogManager.getLogger(AiTestSummaryGenerator.class);

    private final TestSummaryService service;

    public AiTestSummaryGenerator() {
        this(buildModel());
    }

    public AiTestSummaryGenerator(ChatModel model) {
        this.service = AiServices.create(TestSummaryService.class, model);
    }

    /**
     * Main entry: generate summary from surefire XML
     */
    public Path generateSummary() {

        logger.info("=== AI Test Summary Generation Started ===");

        String testData = readSurefireReports();

        if (testData.isBlank()) {
            logger.warn("No surefire data found — skipping summary");
            return null;
        }

        String summary = service.generateSummary(testData);

        if (summary == null || summary.isBlank()) {
            logger.warn("AI returned empty summary — skipping report generation");
            return null;
        }

        return writeReport(summary);
    }

    /**
     * Reads ALL surefire XML files
     */
    private String readSurefireReports() {
        Path dir = Paths.get("target", "surefire-reports");

        if (!Files.exists(dir)) {
            return "";
        }

        StringBuilder content = new StringBuilder();
        int maxFiles = 2; // Limit to avoid sending excessive data to LLM
        int count = 0;

        try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir, "*.xml")) {
            for (Path file : stream) {

                // Only take first 2000 chars per file (safe + no IntelliJ warning)
                String fileContent = Files.readString(file);

                String trimmedContent = fileContent.length() > 2000
                        ? fileContent.substring(0, 2000)
                        : fileContent;

                content.append(trimmedContent).append("\n\n");

                count++;
                if (count >= maxFiles) break;
            }
        } catch (IOException e) {
            logger.error("Error reading surefire reports", e);
        }

        return content.toString();
    }

    /**
     * Writes summary report
     */
    private Path writeReport(String summary) {
        Path path = Paths.get("target", "ai-summary-report.md");

        String content = """
            # AI Test Execution Summary

            > Generated by: AiTestSummaryGenerator
            > Status: DRAFT — requires human validation

            ---
            
            """ + summary;

        try {
            Files.createDirectories(path.getParent());
            Files.writeString(path, content);
            logger.info("Summary report written: {}", path.toAbsolutePath());
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        return path;
    }

    /**
     * SAME buildModel pattern (copied intentionally)
     */
    private static ChatModel buildModel() {
        String provider = ConfigReader.getProperty("ai.provider", "ollama");

        return switch (provider.toLowerCase()) {
            case "openai" -> OpenAiChatModel.builder()
                    .apiKey(System.getenv("OPENAI_API_KEY"))
                    .modelName(ConfigReader.getProperty("ai.openai.model", "gpt-4o"))
                    .temperature(0.2)
                    .build();

            case "ollama" -> OllamaChatModel.builder()
                    .baseUrl(ConfigReader.getProperty("ai.ollama.baseUrl", "http://localhost:11434"))
                    .modelName(ConfigReader.getProperty("ai.ollama.model", "llama3.2"))
                    .timeout(Duration.ofSeconds(300))
                    .temperature(0.2)
                    .build();

            default -> throw new IllegalArgumentException("Unknown provider: " + provider);
        };
    }
}