package com.demo.flightbooking.tests.booking;

import com.demo.flightbooking.pages.ConfirmationPage;
import net.datafaker.Faker;
import org.openqa.selenium.WebDriver;
import org.testng.Assert;
import org.testng.annotations.Test;

import com.aventstack.extentreports.ExtentTest;
import com.demo.flightbooking.model.Passenger;
import com.demo.flightbooking.pages.FlightSelectionPage;
import com.demo.flightbooking.pages.HomePage;
import com.demo.flightbooking.pages.PurchasePage;
import com.demo.flightbooking.tests.base.BaseTest;
import com.demo.flightbooking.utils.ConfigReader;
import com.demo.flightbooking.utils.DriverManager;
import com.demo.flightbooking.utils.ExtentManager;

import java.util.Random;

/**
 * Negative testing: submits invalid data to verify form validation behavior.
 * Uses DataFaker for deterministic invalid inputs.
 */
public class PurchaseFormValidationTest extends BaseTest {

    private static final Faker FAKER = new Faker(new Random(42L));

    /**
     * Negative test: submits invalid data to verify form validation behavior.
     * Uses DataFaker with a fixed seed for deterministic invalid inputs.
     * Expected to fail against applications without server-side validation.
     */
    @Test(
            groups = {"regression"},
            testName = "Verify purchase form validation with invalid data from DataFaker"
        )
    public void testPurchaseWithInvalidData() {
        WebDriver driver = DriverManager.getDriver();
        driver.get(ConfigReader.getApplicationUrl());
        ExtentTest test = ExtentManager.getTest();

        if (test != null) {
            test.info("Testing purchase with invalid data generated by DataFaker");
        }
        logger.info("Starting purchase validation test with invalid data");

        // Hardcode valid flight selection: Paris to Rome
        HomePage homePage = new HomePage(driver);
        Assert.assertTrue(homePage.isHomePageDisplayed(), "Home page is not displayed!");
        homePage.findFlights("Paris", "Rome");

        FlightSelectionPage flightSelectionPage = new FlightSelectionPage(driver);
        Assert.assertTrue(flightSelectionPage.isFlightSelectionPageDisplayed(),
                "Flight Selection Page is not displayed!");
        flightSelectionPage.clickChooseFlightButton();

        // Create invalid passenger data using DataFaker
        PurchasePage purchasePage = new PurchasePage(driver);
        Assert.assertTrue(purchasePage.isPurchasePageDisplayed(), "Purchase Page is not displayed!");
        purchasePage.fillPurchaseForm(new Passenger(
            "Paris",
            "Rome",
            FAKER.name().firstName() + "!@#", // invalid name with special chars
            FAKER.name().lastName(),
            FAKER.address().streetAddress(),
            FAKER.address().city(),  // city
            FAKER.address().state(),
            "",  // empty zipCode
            "Visa",
            "",  // empty cardNumber
            "13",  // invalid month
            "2010",  // expired year
            FAKER.name().fullName() + "!@#", // invalid card name
            30,
            "Male"
        ));

        purchasePage.clickPurchaseFlightButton();

        // Synchronization: wait for page navigation to settle before checking URL.
        ConfirmationPage confirmationPage = new ConfirmationPage(driver);
        confirmationPage.isConfirmationPageDisplayed();

        // IMPORTANT: This assertion intentionally fails against the target application.
        // The target application has no server-side validation — it accepts all input.
        // The test validates expected behavior: invalid data SHOULD be rejected.
        // Failure here exercises: RetryAnalyzer (NON_RETRYABLE), ScreenshotUtils,
        // TestListener failure hooks, and testFailureIgnore pipeline continuation.
        // Against a production app with proper validation, this assertion passes unchanged.
        boolean stillOnPurchase = driver.getCurrentUrl().contains("/purchase.php");
        Assert.assertTrue(stillOnPurchase, "Purchase should have failed with invalid data, but proceeded to confirmation");

    }
}
